#!/usr/bin/env bash

echo "SETUP_FLUTTER_INSTALLATION_PATH=$SETUP_FLUTTER_INSTALLATION_PATH" \
  >> "$GITHUB_ENV"

if [[ $SETUP_FLUTTER_ACTIONS_CACHE == "true" ]]; then
  SETUP_FLUTTER_REF_HEAD="$( \
    git ls-remote https://github.com/flutter/flutter "$SETUP_FLUTTER_REF" \
      | cut -f 1)"
  echo "SETUP_FLUTTER_REF_HEAD=$SETUP_FLUTTER_REF_HEAD" >> "$GITHUB_ENV"

  if [[ $SETUP_FLUTTER_ACTIONS_CACHE_KEY == "" ]]; then
    SETUP_FLUTTER_ACTIONS_CACHE_KEY="flutter-$RUNNER_OS-$SETUP_FLUTTER_REF-$SETUP_FLUTTER_REF_HEAD"
  fi
  echo "SETUP_FLUTTER_ACTIONS_CACHE_KEY=$SETUP_FLUTTER_ACTIONS_CACHE_KEY" \
    >> "$GITHUB_ENV"
fi
